/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoyenneRouteImport } from './routes/moyenne'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as ApiPublicFileRouteImport } from './routes/api/public/file'
import { Route as ApiPublicCloudinaryConfigRouteImport } from './routes/api/public/cloudinary/config'
import { Route as ApiPublicCloudinaryDestroyRouteImport } from './routes/api/public/cloudinary/destroy'
import { Route as ApiPublicCloudinarySignRouteImport } from './routes/api/public/cloudinary/sign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoyenneRoute = MoyenneRouteImport.update({
  id: '/moyenne',
  path: '/moyenne',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFileRoute = ApiPublicFileRouteImport.update({
  id: '/api/public/file',
  path: '/api/public/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudinaryConfigRoute =
  ApiPublicCloudinaryConfigRouteImport.update({
    id: '/api/public/cloudinary/config',
    path: '/api/public/cloudinary/config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudinaryDestroyRoute =
  ApiPublicCloudinaryDestroyRouteImport.update({
    id: '/api/public/cloudinary/destroy',
    path: '/api/public/cloudinary/destroy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudinarySignRoute = ApiPublicCloudinarySignRouteImport.update({
  id: '/api/public/cloudinary/sign',
  path: '/api/public/cloudinary/sign',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/moyenne': typeof MoyenneRoute
  '/resultats': typeof ResultatsRoute
  '/api/public/file': typeof ApiPublicFileRoute
  '/api/public/cloudinary/config': typeof ApiPublicCloudinaryConfigRoute
  '/api/public/cloudinary/destroy': typeof ApiPublicCloudinaryDestroyRoute
  '/api/public/cloudinary/sign': typeof ApiPublicCloudinarySignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/moyenne': typeof MoyenneRoute
  '/resultats': typeof ResultatsRoute
  '/api/public/file': typeof ApiPublicFileRoute
  '/api/public/cloudinary/config': typeof ApiPublicCloudinaryConfigRoute
  '/api/public/cloudinary/destroy': typeof ApiPublicCloudinaryDestroyRoute
  '/api/public/cloudinary/sign': typeof ApiPublicCloudinarySignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/moyenne': typeof MoyenneRoute
  '/resultats': typeof ResultatsRoute
  '/api/public/file': typeof ApiPublicFileRoute
  '/api/public/cloudinary/config': typeof ApiPublicCloudinaryConfigRoute
  '/api/public/cloudinary/destroy': typeof ApiPublicCloudinaryDestroyRoute
  '/api/public/cloudinary/sign': typeof ApiPublicCloudinarySignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/moyenne'
    | '/resultats'
    | '/api/public/file'
    | '/api/public/cloudinary/config'
    | '/api/public/cloudinary/destroy'
    | '/api/public/cloudinary/sign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/moyenne'
    | '/resultats'
    | '/api/public/file'
    | '/api/public/cloudinary/config'
    | '/api/public/cloudinary/destroy'
    | '/api/public/cloudinary/sign'
  id:
    | '__root__'
    | '/'
    | '/moyenne'
    | '/resultats'
    | '/api/public/file'
    | '/api/public/cloudinary/config'
    | '/api/public/cloudinary/destroy'
    | '/api/public/cloudinary/sign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoyenneRoute: typeof MoyenneRoute
  ResultatsRoute: typeof ResultatsRoute
  ApiPublicFileRoute: typeof ApiPublicFileRoute
  ApiPublicCloudinaryConfigRoute: typeof ApiPublicCloudinaryConfigRoute
  ApiPublicCloudinaryDestroyRoute: typeof ApiPublicCloudinaryDestroyRoute
  ApiPublicCloudinarySignRoute: typeof ApiPublicCloudinarySignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moyenne': {
      id: '/moyenne'
      path: '/moyenne'
      fullPath: '/moyenne'
      preLoaderRoute: typeof MoyenneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/file': {
      id: '/api/public/file'
      path: '/api/public/file'
      fullPath: '/api/public/file'
      preLoaderRoute: typeof ApiPublicFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/config': {
      id: '/api/public/cloudinary/config'
      path: '/api/public/cloudinary/config'
      fullPath: '/api/public/cloudinary/config'
      preLoaderRoute: typeof ApiPublicCloudinaryConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/destroy': {
      id: '/api/public/cloudinary/destroy'
      path: '/api/public/cloudinary/destroy'
      fullPath: '/api/public/cloudinary/destroy'
      preLoaderRoute: typeof ApiPublicCloudinaryDestroyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/sign': {
      id: '/api/public/cloudinary/sign'
      path: '/api/public/cloudinary/sign'
      fullPath: '/api/public/cloudinary/sign'
      preLoaderRoute: typeof ApiPublicCloudinarySignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoyenneRoute: MoyenneRoute,
  ResultatsRoute: ResultatsRoute,
  ApiPublicFileRoute: ApiPublicFileRoute,
  ApiPublicCloudinaryConfigRoute: ApiPublicCloudinaryConfigRoute,
  ApiPublicCloudinaryDestroyRoute: ApiPublicCloudinaryDestroyRoute,
  ApiPublicCloudinarySignRoute: ApiPublicCloudinarySignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
